### ISSUE TITLE
Question about polyfilling

### ISSUE THREAD

**Issue by VenatusSimpleX** [web-padawan/vanilla-colorful#19]
Hey, thank you so much for this package, I loved it a lot.

I have a problem where I've been using this package (due to how small and beautiful it is) on my Svelte app, it had no problems until I ported it over to [tauri](https://github.com/tauri-apps/tauri). Tauri uses webview, and on Windows machine, Tauri uses webview from legacy Edge.

I read your README, and found out that your package does not support legacy Edge. So I thought about polyfills, and try to get vanilla-colorful working without needing me to use other packages as alternatives (because frankly, they don't look as good and my styling skills are questionable).

I've found [webcomponent's polyfills](https://github.com/webcomponents/polyfills) and used their [shadydom](https://github.com/webcomponents/polyfills/tree/master/packages/shadydom) and [shadycss](https://github.com/webcomponents/polyfills/tree/master/packages/shadycss) modules. But I am not sure how I can apply their ShadyCSS interface with vanilla-colorful, since I don't know where to apply their `prepareTemplate` function with vanilla-colorful, may I please have some guidance regarding this?

I'm not sure if this is the place to ask questions, but I'm going to give it a shot anyway since I don't really know where else to ask, if this is the wrong place to ask, please do direct me to the correct direction. Thank you so much for your time and effort!

**Comment by web-padawan** [comment]
Hi, thanks for the issue.

 Integrating `ShadyCSS`  is possible but it would increase bundle size which is something I would like to avoid.
I can create a prototype branch and apply the necessary polyfill calls to illustrate how it could be done.

**Comment by VenatusSimpleX** [comment]
That would be nice, thank you!

If you are busy, please do direct me to a general direction and I can try to implement myself?

**Comment by web-padawan** [comment]
Sorry about the lack of response. The project has been rewritten to have only one shadow root per component and fewer templates, but supporting polyfills would require changing internal helper that creates a template to accept a tag name.

I'm not going to add polyfill support at this point, if you are still interested, see the examples: [1](https://github.com/GoogleChromeLabs/howto-components/blob/079d0fa34ff9038b26ea8883b1db5dd6b677d7ba/elements/howto-checkbox/howto-checkbox.js#L60), [2](https://github.com/GoogleChromeLabs/howto-components/blob/079d0fa34ff9038b26ea8883b1db5dd6b677d7ba/elements/howto-checkbox/howto-checkbox.js#L92).
