### ISSUE TITLE
Selecting the hue before saturation/brightness doesn't register properly

### ISSUE THREAD

**Issue by Webbeh** [web-padawan/vanilla-colorful#23]
By having a starting color of #000 or #FFF, if you pick the hue of the new color before the saturation/brightness, the hue is reset when the new saturation/brightness is selected (ie : the correct saturation/brightness will be selected, but for the color red).

I do understand why it may do it, but is there a fix possible, rather than having to start with #010101/#FEFEFE ?

https://youtu.be/fePgS06AVwU

**Comment by web-padawan** [comment]
Thanks for the issue, sorry about the delay. The fix will be included to the next version.
