### ISSUE TITLE
Vue example is broken

### ISSUE THREAD

**Issue by Konfuze** [web-padawan/vanilla-colorful#24]
[Vue example](https://components.studio/edit/xACXVNs47cgdWFSafS70) is broken:
![image](https://user-images.githubusercontent.com/131331/114158945-f05ae980-992d-11eb-84c9-6e6e08d565d5.png)

Update the [index.vue](https://components.studio/edit/xACXVNs47cgdWFSafS70/src/index.vue) to make it work:
`<hex-color-picker :color="color.value" @color-changed="this.handleColorChanged"></hex-color-picker>`
to
`<hex-color-picker :color="color.value" @color-changed="handleColorChanged"></hex-color-picker>`

**Comment by web-padawan** [comment]
Thanks for the issue and suggested fix, and sorry about not answering earlier. Updated the example so now it works.
