### ISSUE TITLE
Consider using CSS instead of SCSS

### ISSUE THREAD

**Issue by pepelsbey** [web-padawan/vanilla-colorful#47]
I couldn’t find any trace of SCSS syntax in [src/lib/styles](https://github.com/web-padawan/vanilla-colorful/tree/master/src/lib/styles), so I wonder if using plain CSS files would be better. Less complicated, more future-proof.

I know that the whole project is 100% pure TypeScript, but at least _there is_ a reason for that 😀 The only use for Sass I could find is to combine and compress files during the build process. I would suggest using [CSSO](https://github.com/css/csso) for that. It would also save you 28 bytes! (1871 vs 1843) Not too much, but every JS byte counts, right?

Sorry for just an issue, not PR. But I hope you’d like the idea.

**Comment by web-padawan** [comment]
Thanks for the suggestion! I agree that it doesn't make sense to use SCSS here. I will update the setup soon.
