### ISSUE TITLE
HEX picker with alpha

### ISSUE THREAD

**Issue by tobyzerner** [web-padawan/vanilla-colorful#69]
Thanks for your great work on this library! 

Is it possible to have a HEX picker including the alpha channel, resulting in 4-byte outputs like `#aabbccff`? I don't see it as an option in the "Available pickers" table.

**Comment by web-padawan** [comment]
Hi, this isn't currently supported. Check out https://github.com/omgovich/react-colorful/issues/161 as I'm using `react-colorful` as a reference.

**Comment by timothyallan** [comment]
It's supported now, we've been using it for a while on react projects. https://github.com/omgovich/react-colorful/blob/a85e5b36b55cae7e95c73c8ecde0bc881e8e3b1f/src/components/HexColorInput.tsx#L10

**Comment by web-padawan** [comment]
Fixed by #81.
