### ISSUE TITLE
Opacity slider?

### ISSUE THREAD

**Issue by oyatek** [web-padawan/vanilla-colorful#7]
Congratulations, the colorpicker looks great. We could use it in our project but we need an opacity slider as well. Can you add it?

**Comment by web-padawan** [comment]
Hi, thanks for the issue. 
There is a PR adding opacity support at https://github.com/omgovich/react-colorful/pull/47. I'm going to port it when it lands.

**Comment by omgovich** [comment]
Doing my best =)

**Comment by web-padawan** [comment]
@oyatek the alpha channel (opacity slider) support is released in `0.3.0` version. Feedback is welcome!
